#ifndef funkcje_h
#define funkcje_h
#include <SDL.h>
#include <stdio.h>
#include <string.h>
bool loadGrayCharset();
bool loadRedCharset();
bool loadTurquoiseCharset();
bool loadVioletCharset();
bool loadYellowCharset();
void DrawString(SDL_Surface* screen, int x, int y, const char* text, SDL_Surface* charset);
void DrawSurface(SDL_Surface* screen, SDL_Surface* sprite, int x, int y);
void DrawPixel(SDL_Surface* surface, int x, int y, Uint32 color);
void DrawLine(SDL_Surface* screen, int x, int y, int l, int dx, int dy, Uint32 color);
void DrawRectangle(SDL_Surface* screen, int x, int y, int l, int k, Uint32 color);
bool init();
void setFullScreen();
bool load();
void drawLives();
void drawTime();
void free();
void resetMovingUp();
void moveHeroAtStart();
void drawEnterName();
void zamien(char napis1[], char napis2[]);
void loadHighScores();
void drawHighScores();
void saveHighscores();
void moveDownTable(int n);
void start();
void startTime();
void die(bool x);
void afterDeath();
void dieToDeath();
void checkDying();
void moveCar1();
void moveCar2();
void moveCar3();
void moveCar4();
void moveCar5();
void moveTurtle1();
void moveTurtle1dive();
void moveLog1();
void moveLog2();
void moveTurtle2();
void moveTurtle2dive();
void moveLog3();
void moveMovingObjects();
void drawCar1();
void drawCar2();
void drawCar3();
void drawCar4();
void drawCar5();
void drawTurtle1();
void drawTurtle1dive();
void drawLog1();
void drawLog2();
void drawTurtle2();
void drawTurtle2dive();
void drawLog3();
void drawMovingObjects();
void animateCars();
void animateTurtles();
bool checkCollisonCarFixed(struct frog hero, struct car car);
bool checkCollisonTruckFixed(struct frog hero, struct car car);
bool checkCollisonTurtleFixed(struct frog hero, struct car car);
bool checkCollisonLogFixed(struct frog hero, struct car car);
bool heroCollidesWithCar();
bool heroCollidesWithTurtle1();
bool heroCollidesWithTurtle1dive();
bool heroCollidesWithLog1();
bool heroCollidesWithLog2();
bool heroCollidesWithTurtle2();
bool heroCollidesWithTurtle2dive();
bool heroCollidesWithLog3();
bool heroCollidesWithFriend();
void checkWater();
void checkBounds();
void checkMovingUp();
void setTimeRect();
void drawTimeRect();
void frogSaved();
void checkHappy();
void drawHappy();
bool allFrogsSaved();
void countTime();
void setMoveLeft();
void setMoveRight();
void setMoveUp();
void setMoveDown();
void moveLeft();
void moveRight();
void moveUp();
void moveDown();
void move();
void drawPause();
void drawQuit();
void drawMap();
void drawHero();
void drawOver(int n);
void drawHud();
void drawEverythingButHud();
void checkIfFinished();
void handleDeath();
bool checkLetter();
bool checkChar();
void handleInput();
void events();
void draw();
void render();
void drawMenuOptions();
void drawMenu();
void playerSelectedOption();
void resetName();
void resetFirstStats();
void resetHighScores();
void drawLastGameFrame();
void eventsMenu();
void eventsHighscores();
void manageFrame0();
void manageFrame1();
void manageFrame2();
void froggerGame();
#endif